---
title: "ProjectReport"
author: "Daniel Hopkins & Rob Verbeek"
date: "11/7/2019"
output: html_document
---

The plan: Implement all the models from the Diabetes example. Then build a hierarchical model with countries as the "machines" and show that it works better than "separate" or "pooled" models.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
library(ggplot2)
library(corrplot)
# library(tidyverse)
# library(caret)
# library(GGally)
# library(bayesplot)
library(rstanarm)
SEED = 1234 
```


## Reading in the ESS Data
```{r read_data}
ESSData <- read.csv(file="data/ESS8e02.1_F1.csv", header=TRUE, sep=",")
```

```{r selecting data rows and variables}
# N = 1000 # Number of sample points

set.seed(1234)

# LIMIT TO ONE COUNTRY
ESSData = subset(ESSData,cntry=="NL")

sampleRows = seq(1,length(ESSData$cntry))

sampleRows = subset(sampleRows, ESSData$lrscale[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$happy[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$aesfdrk[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$sclmeet[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$sclact[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$imwbcnt[sampleRows]<=10)
sampleRows = subset(sampleRows, ESSData$lknemny[sampleRows]<=10)

country <- ESSData$cntry[sampleRows]

lrscale <- ESSData$lrscale[sampleRows] / 10
safety <- ESSData$aesfdrk[sampleRows] / 10 
happy <- ESSData$happy[sampleRows] / 10 
socialMeet <- ESSData$sclmeet[sampleRows] / 10 
socialAct <- ESSData$sclact[sampleRows] / 10 
immigrants <- ESSData$imwbcnt[sampleRows] / 10 
money <- ESSData$lknemny[sampleRows] / 10 

spectrumData = data.frame("safety"=safety, "happy"=happy, "socialMeet"=socialMeet, "socialAct"=socialAct, "immigrants"=immigrants, "money"=money)
# spectrumData = data.frame("safety"=safety, "happy"=happy)

M = length(lrscale)
```

```{r correlation matrix}
corrplot(cor(data.frame(spectrumData,lrscale)))
```

```{r stan glm model}
binary_spectrum = as.integer(lrscale >= 0.5)

t_prior <- student_t(df = 7, location = 0.5, scale = 0.25)
t_prior
post1 <- stan_glm(binary_spectrum ~ ., data = spectrumData,
                 family = binomial(link = "logit"), 
                 prior = t_prior, prior_intercept = t_prior, QR=TRUE,
                 seed = SEED)
post1$coefficients
```
```{r glm plot}
pplot<-plot(post1, "areas", prob = 0.95, prob_outer = 1)
pplot+ geom_vline(xintercept = 0)

round(posterior_interval(post1, prob = 0.9), 2)
(loo1 <- loo(post1, save_psis = TRUE))
post0 <- update(post1, formula = binary_spectrum ~ 1, QR = FALSE)
(loo0 <- loo(post0))
compare_models(loo0, loo1)
```
```{r}
N = 5

data <- list(N = N, M = M, y = lrscale, x = spectrumData)
fit <- stan('spectrum.stan', data = data)
s = extract(fit)
```

```{r}
s
```

```{r checking averages for fun}
#   cAT = 0
#   cNL = 0
#   hAT = 0
#   hNL = 0
# for(i in seq(1,N)) {
#   if(country[i] == "AT" && happy[i]>=0) {
#     cAT = cAT + 1
#     hAT = hAT + happy[i]
#   }
#   if(country[i] == "NL") {
#     cNL = cNL + 1
#     hNL = hNL + happy[i]
#   }
# }
# print(hAT)
# print(cAT)
#   print(hAT/cAT)
#   print(hNL/cNL)
```